### ISSUE TITLE
Undocumented advanced constraint field location_sequence_pattern

### ISSUE THREAD

**Issue by matt-snider** [route4me/route4me-json-schemas#11]
In the schema for route parameter [advanced_constraints](https://github.com/route4me/route4me-json-schemas/blob/33ba0731b42a1ae382f2208e8b40f392e90672ae/RouteParameters.dtd#L417) I don't see any mention of `location_sequence_pattern` although it seems to be present in the Java SDK [AdvancedConstraints.java](https://github.com/route4me/route4me-java-sdk/blob/ae8bd89215885822bd70c76496965c340687d3c5/src/main/java/com/route4me/sdk/services/routing/advancedconstraints/AdvancedConstraints.java#L45) and used in [this example](https://github.com/route4me/route4me-java-sdk/blob/c6f28f611eb4d78e32a71a780bc0ec27317e8032/src/main/java/com/route4me/sdk/examples/advancedconstraints/AdvancedConstraintsExample11.java) from that repo.

**Comment by Olman62** [comment]
The parameters:
"depot_address"
"location_sequence_pattern"
were added to the JSON schema RouteParameters

**Comment by matt-snider** [comment]
@Olman62 Thank you!

**Comment by matt-snider** [comment]
@Olman62 There is still no description which makes it not that helpful. I think it would be useful to document what that property is or does
