### ISSUE TITLE
Plz, enable Travis CI builds

### ISSUE THREAD

**Issue by maxkoryukov** [route4me/route4me-json-schemas#4]
I have added :
* json validation
* schema validation
* travis build 

in #3

But I don't have sufficient permissions to enable build on Travis CI:

----
![selection_018](https://cloud.githubusercontent.com/assets/8887971/22396201/f481649c-e574-11e6-8c2d-62e044059c1c.jpg)
----

Somebody, turn it on , plz;)

@novapulsar @Olman62

**Comment by novapulsar** [comment]
Done

**Comment by novapulsar** [comment]
Appveyor also added to c# and vb.net

**Comment by maxkoryukov** [comment]
Great;)

We have broken build))) It is not a best state;) But it is a step forward!
